# Copyright (c) 2023 Red Hat, Inc.
operator:
  replicas: 1
  rdrtrigger:
    image: quay.io/ecosystem-appeng/regional-dr-trigger-operator:0.3.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  namespace: regional-dr-trigger
