kind: Deployment
apiVersion: apps/v1
metadata:
  name: operator
spec:
  replicas: 0
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: rdrtrigger
    spec:
      serviceAccountName: sa
      securityContext:
        runAsNonRoot: true
      containers:
      - name: rdrtrigger
        image: controller
        imagePullPolicy: IfNotPresent
        args:
          - manager
          - --leader-election
          - --probe-address=:8081
          - --metric-address=127.0.0.1:8080
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
