//go:build !ignore_autogenerated

// Copyright (c) 2023 Red Hat, Inc.

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResilientCluster) DeepCopyInto(out *ResilientCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResilientCluster.
func (in *ResilientCluster) DeepCopy() *ResilientCluster {
	if in == nil {
		return nil
	}
	out := new(ResilientCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResilientCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResilientClusterList) DeepCopyInto(out *ResilientClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResilientCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResilientClusterList.
func (in *ResilientClusterList) DeepCopy() *ResilientClusterList {
	if in == nil {
		return nil
	}
	out := new(ResilientClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResilientClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResilientClusterStatus) DeepCopyInto(out *ResilientClusterStatus) {
	*out = *in
	in.InitialStatus.DeepCopyInto(&out.InitialStatus)
	in.CurrentStatus.DeepCopyInto(&out.CurrentStatus)
	in.PreviousStatus.DeepCopyInto(&out.PreviousStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResilientClusterStatus.
func (in *ResilientClusterStatus) DeepCopy() *ResilientClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ResilientClusterStatus)
	in.DeepCopyInto(out)
	return out
}
