---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: regional-dr-trigger-operator
    app.kubernetes.io/part-of: regional-dr-trigger-operator
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: regional-dr-trigger-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: regional-dr-trigger-role
subjects:
  - kind: ServiceAccount
    name: regional-dr-trigger-sa
    namespace: {{ .Values.operator.namespace }}
