apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: regional-dr-trigger-operator
    app.kubernetes.io/part-of: regional-dr-trigger-operator
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  name: {{ .Values.operator.namespace }}
