---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: regional-dr-trigger-operator
    app.kubernetes.io/part-of: regional-dr-trigger-operator
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: regional-dr-trigger-metrics-service
  namespace: {{ .Values.operator.namespace }}
spec:
  ports:
    - name: metrics
      port: 8383
      protocol: TCP
  selector:
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: regional-dr-trigger-operator
