apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: rdrtrigger-0.2.0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: regional-dr-trigger-operator
    app.kubernetes.io/part-of: regional-dr-trigger-operator
    app.kubernetes.io/version: 0.2.0
  name: regional-dr-trigger-monitoring-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: regional-dr-trigger-monitoring-role
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
