apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: rdrtrigger-0.1.0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: regional-dr-trigger-operator
    app.kubernetes.io/part-of: regional-dr-trigger-operator
    app.kubernetes.io/version: 0.1.0
  name: regional-dr-trigger-sm
namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - regional-dr-trigger
  selector:
    matchLabels:
      app.kubernetes.io/part-of: regional-dr-trigger-operator
