# Copyright (c) 2023 Red Hat, Inc.

apiVersion: v2
name: regional-dr-trigger-operator
description: This Operator will use ODF's Regional DR API for triggering a Failover process for all Applications affiliated with a cluster which is reported as not available by ACM's Managed Cluster API.
version: replace-me
appVersion: "replace-me"
home: https://github.com/RHEcosystemAppEng/regional-dr-trigger-operator
keywords:
  - acm
  - odf
  - openshift
  - regional dr
  - disaster recovery
icon: https://raw.githubusercontent.com/RHEcosystemAppEng/regional-dr-trigger-operator/main/hack/logo-rh-icon-standard-rgb.png
