apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - servicemonitor.yaml
  - role.yaml
  - rolebinding.yaml
patches:
  - target:
      kind: ServiceMonitor
    patch: |
      # override the namespace transformer for the ServiceMonitor
      - op: replace
        path: metadata/namespace
        value: openshift-monitoring
replacements:
  - source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      - select:
          kind: ServiceMonitor
        fieldPaths:
          - spec.namespaceSelector.matchNames.0
