kind: Deployment
apiVersion: apps/v1
metadata:
  name: operator
spec:
  template:
    spec:
      containers:
      - name: kube-rbac-proxy
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1
        imagePullPolicy: IfNotPresent
        args:
          - "--secure-listen-address=0.0.0.0:8383"
          - "--upstream=http://127.0.0.1:8080/"
          - "--logtostderr=true"
          - "--v=0"
        ports:
          - containerPort: 8383
            protocol: TCP
            name: https
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
