kind: Deployment
apiVersion: apps/v1
metadata:
  name: manager
spec:
  replicas: 0
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: sa
      securityContext:
        runAsNonRoot: true
      containers:
      - name: manager
        image: manager-image
        # TODO change to IfNotPresent
        imagePullPolicy: Always
        args:
          - manager
          - --agent-image=manager-image
          - --service-account=sa
          - --controller-leader-election
          - --controller-probe-address=:8081
          - --controller-metric-address=127.0.0.1:8080
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
