namespace: open-cluster-management
namePrefix: multicluster-resiliency-addon-
resources:
  - deployment.yaml
  - addondeploymentconfig.yaml
  - clustermanagementaddon.yaml
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: manager-workload
images:
  - name: manager-image
    newName: manager-image
    newTag: replace-me
configurations:
  - kustomizeconfig.yaml
replacements:
  - path: kustomizereplace.yaml
generatorOptions:
  disableNameSuffixHash: true
