# selective injection of the name prefix (done to avoid injecting the ClusterManagementAddOn)
namePrefix:
  - kind: Deployment
    path: metadata/name
  - kind: AddOnDeploymentConfig
    path: metadata/name

namespace:
# set namespace for default configuration for ClusterManagementAddOn
  - kind: ClusterManagementAddOn
    path: spec/supportedConfigs/defaultConfig/namespace
