---
name: Chart Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'config/**'
      - 'hack/**'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  chart:
    runs-on: ubuntu-latest
    name: Generate and Lint Helm Chart
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Cache tools
        uses: actions/cache@v4
        with:
          path: ./bin
          key: ${{ runner.os }}-bin-${{ hashFiles('Makefile') }}

      - name: Install yq
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          yq: latest

      - name: Generate chart
        run: |
          make chart USER=ecosystem-appeng
          git diff --exit-code

      - name: Lint chart
        run: make lint-chart
